language: rust
sudo: false
cache: cargo
rust:
- stable
- nightly
matrix:
  allow_failures:
  - rust: nightly
env:
  global:
    secure: jLBBZyOyIp5fNFV9AzByeHvDDFEEVsaGlUrVhOmcw/hTZYy55ElG1Ju8ItB+nnEBTR2CydRLqjB8Ti0sDjXQ5iHdSzsKXQXOjVKuCDEwFp1LErCf5xuol7VmQeIE7WkaHfz8xq//kbG6vKqPY1hkMNXwgESyZLQ52yvE+qXqrtJJa5XOF15RZpVGu/Bs7svqDvElsUMDuCKY5b/p4JI//rJ04XlWu9oH5SpjjJTOJqwJuTW3Wzp6eeCeIBVt4iDJMcfFfodNAeuYrp4Cjc9RVW/oFkYautnLm4S48PeBmHcJtfgzwv1mtG2I0caXVD675ZdF926ErrPBMO7aH9YSuRhGnvCCbsKafrw9RkfOwQZc3XCluxOtx+TK/JxQiRFaomOHIzyWb6ts80/6N0fMFDMmQL1A5cPwbPzIa2EtkRoiUIwq7aDOx2KFsvE+cleGK0OQBoko7DLCRENXxMUwJSW7NWH5NdGW/lRMvni2DYajDT/zcTWkSzc/1QedmEWOsnitEddmW/LFq5AWRWlRh2AexO46TDBMSGRbHSfes2x2Cf9dzhDGX6av9WiwlbqS+tP9JtcEqpr74UmXsUsnwbGqwYEQ0vpkhDe2iqE8cZ95XGvQoBEzI6qDfc8oMNmetov/jcejBOP2ebaGkU4KvYuxoX/sgtP8p5KLfEnw4Sg=
script:
- cargo build --verbose
- cargo test --verbose
after_success:
- |
  [ $TRAVIS_RUST_VERSION = stable ] &&
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo publish --token ${CRATESIO_TOKEN}
